language: scala
jdk:
  - openjdk7
scala:
  - 2.11.5
#  - 2.10.4
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION test && ./.check-diff.sh && sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - sbt ++$TRAVIS_SCALA_VERSION clean $(if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then echo "publish"; fi)
env:
  global:
    # travis encrypt -r fommil/freeslick SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r fommil/freeslick SONATYPE_PASSWORD=<PASSWORD>
    - secure: "jUnJZOpreXG7KHoJJUWz8/iX778yhwH1iotVvgc4BuVp8RoJ0XBJraiFJ0Bj44PmEc+k5as2j7zmyX5CHB/whN03Z1aM85061ZAsePyBsId90ZKSlzqxn6xKyBz7SgbuTQMWySc1AUH/qvX8DI5lNTlwGHAozne6MYAnabOJq/A="
    - secure: "k4v1OnVulY+6XDO5YvIPrCZ38P/wFkjfW7c0v2YFSHvU2OBauL9Y99fx7qI7a9LXC6LxDBy4B3FYIzxJEUitn//UfrcPkRa3LF0MrTyPDZC0tsYB+bbnnnrtWkXurhdm/nojCo+4mmunPcyvQQwth8PCZh/p+6Ilq3we5gTUjFI="
